apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    password: AgAwnDcCIMGHim8/ax6Zu/PAiltBZLphuVxTpiXPgQBRgP7vdwLRiQOCF0abQKI44HAldVwka1ucDQQo52SfnFoSl7T7Rb5zZScHxjVl68NO2wynNARjX3yvPGxnuBjBn0mZHG+Iah0gNm80vEI3FUM6uRlgQPMqNu77PNL8wdpgTMpDkP29FNjf5Fz1Cd1a4Iet3eGyb1ppU5LH/YM2+pj8zmEQNVVGBotgaom9xpyJcHVIex4hGNlXd/Biy9T9+C2u0OLFq6GykCPt822cJgEyeifTx6fLUOAwmKwqNYWLbClyP6nUmz7p+lkLCbpAng1454x0EP1iMTAtt/cvcud42XoLmiD3U4HMHemjuiitKr5HOnZYFakqXh4wFXfPtqnL9vQ28+Jnsgbofdk7KtpMzZFaQk2dgOYu9rRORMqHiu9Yz53+gs88qTgxH2er0eXg25yqS+BhZ7X/grdUTGMV87odqETh+VPFxHnkTjzH2EawdEcNdL3MCsWhu7d3FFGB94z75YlpxySMVG3ZCz/GO74vHVlMMHdHVgTy07H3j49jNw0VBoZuLLzIhCZ/g2W8JDD7Rddg3dkyhGaDr9Ec6JsFl2aTrtW7I8St/7pCvBABgG2Rt5+3rwN1sk/gEJxGOY7lAb5k53izK27QJtyAFXT8nzbi0Uw/QwWlf3+RVey3sSCyyiLYRRL/TLgEBvWGANp1rAGXkBpr8dFa462JWiTLy8+n
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: default
